name: Python matrix CI

on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-26, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Trim CI agent
      run: |
        chmod +x contrib/free_disk_space.sh
        ./contrib/free_disk_space.sh
    - name: Install dependencies
      run: |
        uv sync --all-extras --all-packages --dev
        npm install -g @cyclonedx/cdxgen
    - name: Test with pytest
      run: |
        uv run pytest --cov=depscan test
        uv run depscan --config .config/depscan-dev.toml
      env:
        SCAN_DEBUG_MODE: debug
    - name: purl tests
      run: |
        uv run depscan --purl "pkg:pypi/requests@2.32.1"
        uv run depscan --purl "pkg:pypi/requests@4.0.0"
        uv run depscan --purl "pkg:pypi/reqwestss@0.1.0"
        uv run depscan --purl "pkg:npm/%40appthreat/cdxgen@7.0.5"
        uv run depscan --purl "pkg:npm/%40appthreat/cdxgen@7.1.0"
        uv run depscan --purl "pkg:npm/fsevents@1.2.10"
        uv run depscan --purl "pkg:npm/@biomejs/biome@1.8.1"
      env:
        PYTHONIOENCODING: utf-8

  devenv:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-26]
    steps:
    - uses: actions/checkout@v4
    - name: Trim CI agent
      run: |
        chmod +x contrib/free_disk_space.sh
        ./contrib/free_disk_space.sh
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Build the devenv shell
      run: |
        mkdir -p $HOME/.local/share/pnpm/global
        echo "$HOME/.local/share/pnpm/global" >> $GITHUB_PATH
        devenv test
    - name: Run pytest with uv
      run: |
        devenv shell uv run pytest --cov=depscan test
        devenv shell uv run depscan --config .config/depscan-dev.toml
    - name: Run pytest with uv
      run: |
        devenv shell uv run depscan --purl "pkg:pypi/requests@2.32.1"
        devenv shell uv run depscan --purl "pkg:pypi/reqwestss@0.1.0"
